apps/movies/urls.py
from django.urls import path
from .views import MovieListView, MovieDetailView, MovieCreateView, MovieUpdateView, PersonCreateView, RatingView, LongRunningView

app_name = 'apps.movies'

urlpatterns = [
    path('', MovieListView.as_view(), name='movie_list'),
    path(r'<int:pk>/', MovieDetailView.as_view(), name='movie_details'),
    path(r'add/movie/', MovieCreateView.as_view(), name='movie_add'),
    path(r'update/movie/<int:pk>', MovieUpdateView.as_view(), name='movie_update'),
    path(r'add/person/', PersonCreateView.as_view(), name='person_add'),
    path('rating/', RatingView.as_view(), name='rating'),
    path('long_running/', LongRunningView.as_view(), name='long_running'),
]

urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(('django.contrib.auth.urls', 'auth'), namespace='auth')),
    path('authentication/', include('apps.authentication.urls', namespace='authentication')),
    path('', include('apps.movies.urls', namespace='movies')),
]

apps/movies/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Movie(models.Model):
    class TitleType(models.TextChoices):
        SHORT = 'short', _('Short')
        MOVIE = 'movie', _('Movie')

    imdb_id = models.CharField(_('imdb id'), unique=True, max_length=255, null=True)
    name = models.CharField(_('Name'), max_length=255)
    title_type = models.CharField(_('Type of a title'), max_length=80, choices=TitleType.choices, default=TitleType.SHORT)
    is_adult = models.BooleanField(_('Adult rated'), default=False)
    year = models.DateField(_('Release year'), null=True)
    genres = ArrayField(models.CharField(_('Genres'), max_length=80, default=list))
    persons_participating = models.ManyToManyField('movies.Person', through='PersonMovie')

    @property
    def director(self):
        director = self.personmovie_set.filter(category='director').first()
        if director:
            return director.person
        else:
            return 'N/A'

    def __str__(self):
        return f'{self.name}'


class Person(models.Model):
    imdb_id = models.CharField(_('nconst'), max_length=10, null=True, blank=True)
    name = models.CharField(_('Name'), max_length=255, null=True, blank=True)
    birth_year = models.DateField(_('Birth date'), null=True)
    death_year = models.DateField(_('Death date'), null=True)
    movies_participating = models.ManyToManyField('movies.Movie', through='PersonMovie')

    def __str__(self):
        return f'{self.name}'


class PersonMovie(models.Model):
    class Meta:
        ordering = ['-person_id']

    movie = models.ForeignKey(Movie, on_delete=models.PROTECT, null=True, blank=True)
    person = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, blank=True)
    order = models.IntegerField(_('ordering'), null=True, blank=True)
    category = models.CharField(_('Category'), max_length=100, null=True, blank=True)
    job = models.CharField(_('Job'), max_length=100, null=True, blank=True)
    characters = ArrayField(models.CharField(_('Characters'), max_length=255), null=True, blank=True)

apps/movies/forms.py
from operator import itemgetter
from django.forms import ModelForm
from django import forms
from apps.movies.models import Movie, Person
from django.utils.translation import ugettext_lazy as _


class MovieForm(ModelForm):
    class Meta:
        model = Movie
        exclude = ['imdb_id']

    director_list = []
    for person in Person.objects.all():
        if person.personmovie_set.filter(category='director'):
            director_list.append(person)
        else:
            continue
    choices = [(director.id, director.name) for director in director_list]
    director = forms.ChoiceField(choices=sorted(choices, key=itemgetter(1)))


class PersonForm(ModelForm):
    class Meta:
        model = Person
        exclude = ['imdb_id']

    CATEGORY_CHOICES = [
        ('', '--------'),
        (1, _('actor')),
        (2, _('actress')),
        (3, _('cinematographer')),
        (4, _('composer')),
        (5, _('director')),
        (6, _('editor')),
        (7, _('producer')),
        (8, _('self')),
        (9, _('writer'))
    ]

    JOB_CHOICES = [
        ('', '--------'),
        (1, _('co-director')),
        (2, _('comic strip')),
        (3, _('director of photography')),
        (4, _('novel')),
        (5, _('play')),
        (6, _('poem')),
        (7, _('producer')),
        (8, _('scenario')),
        (9, _('screen play')),
        (10, _('story')),
        (11, _('writer'))
    ]

    category = forms.ChoiceField(choices=CATEGORY_CHOICES)
    job = forms.ChoiceField(choices=JOB_CHOICES)
    characters = forms.CharField(max_length=255)

apps/movies/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, TemplateView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from apps.movies.models import Movie, Person
from .forms import MovieForm, PersonForm
from django.urls import reverse_lazy
from django.db import connection
from django.http import HttpResponse
from time import sleep
import logging


logger = logging.getLogger(__name__)


class SearchMixin:
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(name__icontains=self.request.GET.get('q', ''))


class MovieListView(SearchMixin, ListView):
    template_name = 'movies/list.html'
    model = Movie
    context_object_name = 'movies'
    paginate_by = 20


class MovieDetailView(DetailView):
    template_name = 'movies/detail.html'
    model = Movie
    context_object_name = 'movie'


class MovieCreateView(LoginRequiredMixin, CreateView):
    template_name = 'movies/add_movie.html'
    model = Movie
    form_class = MovieForm

    def get_success_url(self):
        return reverse_lazy('movies:movie_details', kwargs={'pk': self.object.pk})


class MovieUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'movies/update_movie.html'
    model = Movie
    form_class = MovieForm

    def get_success_url(self):
        return reverse_lazy('movies:movie_details', kwargs={'pk': self.object.pk})


class PersonCreateView(LoginRequiredMixin, CreateView):
    template_name = 'movies/add_person.html'
    model = Person
    form_class = PersonForm
    success_url = reverse_lazy('movies:movie_list')


class RatingView(TemplateView):
    template_name = 'movies/rating.html'

    @staticmethod
    def actors_rating():
        with connection.cursor() as cursor:
            cursor.execute('''
                SELECT movies_person.name, sum(sq.rating) as rating from movies_person
                join movies_personmovie on movies_personmovie.person_id = movies_person.id
                join (Select movies_movie.id as "movie_id", sum(sq.rating) as rating from movies_movie
                join movies_personmovie on movies_personmovie.movie_id = movies_movie.id
                join (Select movies_person.id AS "person_id", count(*) as rating from movies_person
                join public.movies_personmovie on movies_person.id = movies_personmovie.person_id
                where
                    movies_personmovie.category = 'actor' or
                    movies_personmovie.category = 'actress' or
                    movies_personmovie.category = 'self'  
                group by movies_person.id) as sq on sq.person_id = movies_personmovie.person_id
                group by movies_movie.id) as sq on sq.movie_id = movies_personmovie.movie_id
                where
                    movies_personmovie.category = 'actor' or
                    movies_personmovie.category = 'actress' or
                    movies_personmovie.category = 'self'
                group by movies_person.name
                order by rating DESC;
            ''')
            all_actors_rating = cursor.fetchall()
        actors_rating = all_actors_rating[:10]
        return actors_rating

    @staticmethod
    def movies_rating():
        with connection.cursor() as cursor:
            cursor.execute('''
                SELECT movies_movie.name, sum(sq.rating) as rating from movies_movie
                join movies_personmovie on movies_personmovie.movie_id = movies_movie.id
                join (Select movies_person.id AS "person_id", count(*) as rating from movies_person
                left outer join public.movies_personmovie on movies_person.id = movies_personmovie.person_id
                where
                    movies_personmovie.category = 'actor' or
                    movies_personmovie.category = 'actress' or
                    movies_personmovie.category = 'self'  
                group by movies_person.id) as sq on sq.person_id = movies_personmovie.person_id
                group by movies_movie.id
                order by rating desc;
            ''')
            all_movies_rating = cursor.fetchall()
        movies_rating = all_movies_rating[:10]
        return movies_rating

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['actors_rating'] = self.actors_rating()
        context['movies_rating'] = self.movies_rating()
        return context


class LongRunningView(View):
    @staticmethod
    def get(request):
        logger.error('starting...')
        sleep(10)
        logger.error('Ok')
        return HttpResponse('Ok')

apps/movies/templates/movies/add_movie.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block title %}
    | Add movie
{% endblock %}

{% block content %}
    <div class="col-md-3">
        <h4>Add movie</h4>
        <form method="post">
            {% csrf_token %}
            {{ form|bootstrap }} <br>
            <div class="form-group">
                <button type="submit" class="btn btn-dark">Submit</button>
                <a href="javascript:history.back()" role="button" class="btn btn-dark">Back</a>
            </div>
        </form>
    </div>
{% endblock %}

apps/movies/templates/movies/add_person.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block title %}
    | Add person
{% endblock %}

{% block content %}
    <div class="col-md-3">
        <h4>Add person</h4>
        <form method="post">
            {% csrf_token %}
            {{ form|bootstrap }} <br>
            <div class="form-group">
                <button type="submit" class="btn btn-dark">Submit</button>
                <a href="javascript:history.back()" role="button" class="btn btn-dark">Back</a>
            </div>
        </form>
    </div>

{% endblock %}

apps/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block title %}
    | Details
{% endblock %}

{% block content %}
    <div class="col-md-3">
        <div class="card-body">
            <h4>{{ movie.name }}</h4>
                <p>Type of a title: {{ object.title_type }}</p>
                <p>Directed by: {{ movie.director }}</p>
                <p>Released in: {{ movie.year }}</p>
                {% if movie.is_adult %}
                    <p>PG: 18</p>
                {% endif %}
                {% for genre in movie.genres %}
                    <span class="badge bg-dark text-light">{{ genre }}</span>
                {% endfor %}
        </div>
    </div>

    <div class="col-md-12">
        <div class="card-body">
            <h4>Participants:</h4>
            <table class="participants" >
                <thead>
                <tr>
                    <td><h6>Name</h6></td>
                    <td><h6>Category</h6></td>
                    <td><h6>Job</h6></td>
                    <td><h6>Characters</h6></td>
                </tr>
                </thead>
                <tbody>
                {% for personmovie in object.personmovie_set.all %}
                <tr>
                    <td>{{ personmovie.person }}</td>
                    <td>{{ personmovie.category|default:'N/A'}}</td>
                    <td>{{ personmovie.job|default:'N/A'}}</td>
                    <td>{{ personmovie.characters|join:', '|default:'N/A' }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="col-md-3">
        <div class="card-body">
            <a href="{% url 'movies:movie_update' pk=movie.id%}" role="button" class="btn btn-dark">Update movie</a>
            <a href="javascript:history.back()" role="button" class="btn btn-dark">Back</a>
        </div>
    </div>
{% endblock content %}

apps/movies/templates/movies/list.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}

{% block title %}
    | Movies
{% endblock %}

{% block content %}
{% for movie in movies %}
    <div class="col-md-3">
        <a href="{% url 'movies:movie_details' pk=movie.id %}" class="movies-list">
            <img src="https://i.ytimg.com/vi/z9qOOfVipdw/hqdefault.jpg" class="card-img-top" alt="...">
            <div class="card-body">
                <h4>{{ movie.name }}</h4>
                    <p>Directed by: {{ movie.director }}</p>
                    <p>Released in: {{ movie.year }}</p>
                    {% if movie.is_adult %}
                        <p>PG: 18</p>
                    {% endif %}
                    {% for genre in movie.genres %}
                        <span class="badge bg-dark text-light">{{ genre }}</span>
                    {% endfor %}
            </div>
        </a>
    </div>
{% endfor %}
{% bootstrap_paginate page_obj range=10 extra_pagination_classes="justify-content-center" %}
{% endblock %}

apps/movies/templates/movies/rating.html
{% extends 'base.html' %}

{% block title %}
    | Ratings
{% endblock %}

{% block content%}
    <div class="col-md-6">
        <div class="card-body">
            <h4>Top 10 actors:</h4>
            <ol>
            {% for actor in actors_rating %}
                <li>{{ actor|join:': '}} point(s)</li>
            {% endfor %}
            </ol>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card-body">
            <h4>Top 10 movies:</h4>
            <ol>
            {% for movie in movies_rating %}
                <li>{{ movie|join:': ' }} point(s)</li>
            {% endfor %}
            </ol>
        </div>
    </div>

    <div class="col-md-3">
        <div class="card-body">
           <a href="javascript:history.back()" role="button" class="btn btn-dark">Back</a>
        </div>
    </div>
{% endblock %}

apps/movies/templates/movies/update_movie.html
{% extends 'base.html' %}

{% block title %}
    | Update movie
{% endblock %}

{% load bootstrap %}
{% block content %}
    <div class="col-md-3">
        <form method="post">
            <h4>Update movie</h4>
            {% csrf_token %}
            {{ form|bootstrap }} <br>
            <div class="form-group">
                <button type="submit" value="Update" class="btn btn-dark">Update</button>
                <a href="javascript:history.back(-2)" role="button" class="btn btn-dark">Back</a>
            </div>
        </form>
    </div>
{% endblock %}