apps/authentication/urls.py
from django.urls import path
from .views import UserView, UserListView, SignUpView, ActivateView

app_name = 'apps.authentication'

urlpatterns = [
    path('', UserView.as_view(), name='user'),
    path('users/', UserListView.as_view(), name='users'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path(r'activate/<str:uidb64>/<str:token>/', ActivateView.as_view(), name='activate')
]

apps/movies/urls.py
from django.urls import path
from .views import MovieListView, MovieDetailView, MovieCreateView, MovieUpdateView, PersonCreateView, RatingView, LongRunningView

app_name = 'apps.movies'

urlpatterns = [
    path('', MovieListView.as_view(), name='movie_list'),
    path(r'<int:pk>/', MovieDetailView.as_view(), name='movie_details'),
    path(r'add/movie/', MovieCreateView.as_view(), name='movie_add'),
    path(r'update/movie/<int:pk>', MovieUpdateView.as_view(), name='movie_update'),
    path(r'add/person/', PersonCreateView.as_view(), name='person_add'),
    path('rating/', RatingView.as_view(), name='rating'),
    path('long_running/', LongRunningView.as_view(), name='long_running'),
]

urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(('django.contrib.auth.urls', 'auth'), namespace='auth')),
    path('authentication/', include('apps.authentication.urls', namespace='authentication')),
    path('', include('apps.movies.urls', namespace='movies')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>proj

            {% block title %}
            {% endblock title %}

        </title>
        <link href="/static/bootstrap.min.css" rel="stylesheet">
        <link href="/static/main.css" rel="stylesheet">

        {% block extra_href %}
        {% endblock extra_href %}

    </head>
    <body>

        {% block header %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark nav-dark">
            <div class="container">
            <a class="navbar-brand" href="{% url 'movies:movie_list' %}">Movies</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'movies:movie_add' %}">Add movie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'movies:person_add' %}">Add person</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'movies:rating' %}">Ratings</a>
                        </li>
                        <li>
                            <form class="form-inline" method="get">
                                <input type="search" placeholder="Search" name="q"  value="{{ request.GET.q }}">
                                <input class="btn btn-outline-light" type="submit" value="Search">
                            </form>
                        </li>
                        <li class="nav-item dropdown">
                            {% if not request.user.is_authenticated %}
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownNotAuthenticated" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Account
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'auth:login' %}">Log in</a>
                                <a class="dropdown-item" href="{% url 'authentication:signup' %}">Sign up</a>
                            </div>
                            {% else%}
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAuthenticated" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Hi, <b>{{ request.user.username }}</b>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'auth:logout' %}">Log Out</a>
                                <a class="dropdown-item" href="{% url 'authentication:user' %}">User Info</a>
                            </div>
                            {% endif%}
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <br>
        {% endblock header %}

        <div id="container" class="container">
            <div class="row">

                {% block content %}
                {% endblock content %}

            </div>
            <br>
            <div class="row">

                {% block footer %}
                {% endblock footer  %}

            </div>
            <script src="/static/jquery.min.js"></script>
            <script src="/static/popper.min.js"></script>
            <script src="/static/bootstrap.min.js"></script>

            {% block extra_js %}
            {% endblock extra_js %}

        </div>
    </body>
</html>