apps/authentication/urls.py
from django.urls import path
from .views import UserView, UserListView, SignUpView, ActivateView

app_name = 'apps.authentication'

urlpatterns = [
    path('', UserView.as_view(), name='user'),
    path('users/', UserListView.as_view(), name='users'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path(r'activate/<str:uidb64>/<str:token>/', ActivateView.as_view(), name='activate')
]

urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(('django.contrib.auth.urls', 'auth'), namespace='auth')),
    path('authentication/', include('apps.authentication.urls', namespace='authentication')),
    path('', include('apps.movies.urls', namespace='movies')),
]

apps/authentication/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

apps/authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required. Enter your email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

apps/authentication/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, CreateView, View
from django.contrib.messages.views import SuccessMessageMixin
from .forms import SignupForm
from django.urls import reverse_lazy
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.http import HttpResponse, HttpResponseRedirect
from .tokens import account_activation_token
from django.template.loader import render_to_string
from .tasks import send_verification_email
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth import login


User = get_user_model()


class UserView(LoginRequiredMixin, TemplateView):
    template_name = 'authentication/user.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = User.objects.get(username=self.request.user)
        return context


class UserListView(LoginRequiredMixin, TemplateView):
    template_name = 'authentication/users.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = User.objects.all()
        return context


class SignUpView(SuccessMessageMixin, CreateView):
    template_name = 'authentication/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('authentication:signup')
    success_message = 'Please confirm your email address to complete the registration'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.is_active = False
        self.object.save()

        current_site = get_current_site(self.request)
        body = {'user': self.object.username,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(self.object.pk)),
                'token': account_activation_token.make_token(self.object),
                }
        subject = 'Activate your account'
        message = render_to_string('authentication/email_confirmation.html', body)
        recipient = self.object.email
        send_verification_email.delay(subject, message, recipient)
        return super().form_valid(form)


class ActivateView(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return HttpResponseRedirect(reverse_lazy('movies:movie_list'))
        else:
            return HttpResponse('Activation link is invalid!')

apps/authentication/templates/authentication/acc_active_email.html
{% autoescape off %}
{% csrf_token %}

Hi {{ user }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'authentication:activate' uidb64=uid token=token %}

{% endautoescape %}

apps/authentication/templates/authentication/email_confirmation.html
{% autoescape off %}
{% csrf_token %}

    Hi {{ user }},
    Please click on the button to confirm your registration
    http://{{ domain }}{% url 'authentication:activate' uidb64=uid token=token %}">

{% endautoescape %}

apps/authentication/templates/authentication/register.html
{% extends 'base.html' %}

{% block title %}
    | Register
{% endblock title %}

{% block content %}
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
        <div>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
            <small style="display: none">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
            {% endfor %}
        </div>
        {% endfor %}<br>
        <button type="submit" class="btn btn-primary">Sign up</button>
    </form>
{% endblock %}

{% block footer %}
<div>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif  %}
</div>
{% endblock %}

apps/authentication/templates/authentication/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    | Sign up
{% endblock title %}

{% block content %}
    <div class="col-md-4">
        <h4>Sign up</h4>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group">
                <button type="submit" class="btn btn-dark">Sign up</button>
                <a href="javascript:history.back()" role="button" class="btn btn-dark">Back</a>
            </div>
        </form>
    </div>
{% endblock %}

{% block footer %}
    <div class="col-md-3">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif  %}
    </div>
{% endblock %}

apps/authentication/templates/authentication/user.html
{%  extends 'base.html' %}

{% block title %}
    | User info
{% endblock title %}

{% block content %}
    <div class="col-md-3">
        <h4>Hi, {{ user.username }}!</h4>
            <p>Registration date: {{ user.date_joined }}</p>
            <p>User status: {% if user.is_superuser %} admin {% else %} regular {% endif %}</p>
            <p>Email: {{ user.email }}</p>
            <p>Last log in: {{ user.last_login }}</p>
        <a href="javascript:history.back()" role="button" class="btn btn-dark">Back</a>
    </div>

{% endblock content %}

apps/authentication/templates/authentication/users.html
{%  extends 'base.html' %}

{% block title %}
    | Users info
{% endblock title %}

{% block content %}
    <div class="col-md-3">
        <h4>Users</h4>
            <h6>Total: {{ users|length }} user(s)</h6>
            <h6>List of users:</h6>
                <ol>
                {% for user in users %}
                    <li><b>{{ user }}</b> ({% if user.is_superuser %}admin{% else %}regular{% endif %}): {{ user.email }}</li>
                {% endfor %}
                </ol>
            <a href="javascript:history.back()" role="button" class="btn btn-dark">Back</a>
    </div>
{% endblock content %}